networks:
  monitoring:
    external: true
    name: monitoring

services:
  kitty-website:
    image: forgejo.iamnotgerman.de/root/lets_adopt_a_kitty:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: kitty-website
    restart: unless-stopped
    networks:
      - monitoring
    environment:
      # this created a shared loation for the multiple gunicorn worker processes to share state
      # this makes things like Counter not be indeterminate when querying state
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus_multiproc
    # volumes:
    #   # I forgot why this was recommended, or why it was removed honestly
    #   - .:/app  
    ports:
      - "8006:8000"
    command: >
      rm -rf /tmp/prometheus_multiproc/* && gunicorn  --bind 0.0.0.0:8000 
              --workers 3 
              --timeout 60 
              kitty_website.wsgi:application
    # python manage.py runserver 0.0.0.0:8000
